### ISSUE TITLE
Server crashes caused by fairy lights mod

### ISSUE THREAD

**Issue by alexbobp** [copygirl/obsidian_packs#18]
```
[00:50:04] [Server thread/INFO] [net.minecraft.server.management.PlayerList]: AniMaided[/45.22.138.1:59556] logged in with entity id 32640 at (-623.7213089832229, 91.0, 9.5)
[00:50:04] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: AniMaided joined the game
[00:50:05] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0-u252]
Caused by: java.lang.NullPointerException
        at com.pau101.fairylights.server.fastener.connection.type.Connection.update(Connection.java:290) ~[Connection.class:?]
        at com.pau101.fairylights.server.fastener.FastenerDefault.update(FastenerDefault.java:77) ~[FastenerDefault.class:?]
        at com.pau101.fairylights.server.block.entity.BlockEntityFastener.func_73660_a(BlockEntityFastener.java:69) ~[BlockEntityFastener.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1838) ~[amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
        ... 4 more
[00:50:05] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: /home/game/obsidian12pack/./crash-reports/crash-2020-06-22_00.50.05-server.txt
```

Apparently this crash kept happening upon Maid trying to join.

**Comment by alexbobp** [comment]
Akane has reproduced the crash.  It happens when getting close to Sahfy's base aka Suzy's mine.

**Comment by copygirl** [comment]
@Empour had pushed a slab into her fairy light with a piston. Maybe that moved the block entity, and Fairy Lights does not expect that? Resolved for now by temporarily removing the mod, then adding it back. If nobody tries something similar again, we should be safe.

Reported at pau101/Fairy-Lights#74.

**Comment by copygirl** [comment]
The issue was resolved by the mod, but I think we updated mods just a couple hours before Fairy Lights released a new version, so it's not currently in the latest pack version. Will close when we do another update!
