### ISSUE TITLE
Crash in northwestern snow biome

### ISSUE THREAD

**Issue by Lumieos** [copygirl/obsidian_packs#7]
After entering a snow biome northwest of spawn, a repeated crash occurrs after warning me that CCL caught a rendering exception.

The end of the crash is as follows, but this text is repeated many times prior to the end, referencing a variety of different coordinates.

---

```
[21:37:06] [Chunk Batcher 22/ERROR] [CodeChickenLib]: 
 CCL has caught an exception whilst rendering a block
  BlockPos:      x:-599, y:61, z:-144
  Block Class:   class net.minecraft.block.BlockStaticLiquid
  Registry Name: minecraft:water
  Metadata:      0
  State:         minecraft:water[level=0]
 Tile at position
  Tile Class:    null
  Tile Id:       null
  Tile NBT:      null
You can turn off player messages in the CCL config file.

net.minecraft.util.ReportedException: Tesselating block model
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:95) ~[bvm.class:?]
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:82) [CCBlockRendererDispatcher.class:?]
	at mods.betterfoliage.client.Hooks.renderWorldBlock(Hooks.kt:95) [Hooks.class:?]
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:200) [bxr.class:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100) [bxn.class:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43) [bxn.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Coordinate out of bounds!
	at sun.awt.image.ByteInterleavedRaster.getDataElements(Unknown Source) ~[?:1.8.0_251]
	at java.awt.image.BufferedImage.getRGB(Unknown Source) ~[?:1.8.0_251]
	at pl.asie.mage.plugins.customColors.CustomColorBlocks.lambda$applyBiome$1(CustomColorBlocks.java:116) ~[CustomColorBlocks.class:?]
	at net.minecraft.world.biome.BiomeColorHelper.func_180285_a(SourceFile:36) ~[anj.class:?]
	at pl.asie.mage.plugins.customColors.CustomColorBlocks.applyBiome(CustomColorBlocks.java:114) ~[CustomColorBlocks.class:?]
	at pl.asie.mage.plugins.customColors.CustomColorBlocks.lambda$override$0(CustomColorBlocks.java:92) ~[CustomColorBlocks.class:?]
	at net.minecraft.client.renderer.color.BlockColors.func_186724_a(BlockColors.java:185) ~[bik.class:?]
	at net.minecraftforge.client.model.pipeline.BlockInfo.getColorMultiplier(BlockInfo.java:63) ~[BlockInfo.class:?]
	at net.minecraftforge.client.model.pipeline.VertexLighterFlat.processQuad(VertexLighterFlat.java:164) ~[VertexLighterFlat.class:?]
	at net.minecraftforge.client.model.pipeline.QuadGatheringTransformer.put(QuadGatheringTransformer.java:66) ~[QuadGatheringTransformer.class:?]
	at net.minecraftforge.client.model.pipeline.UnpackedBakedQuad.pipe(UnpackedBakedQuad.java:78) ~[UnpackedBakedQuad.class:?]
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:116) ~[ForgeBlockModelRenderer.class:?]
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:81) ~[ForgeBlockModelRenderer.class:?]
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:47) ~[bvo.class:?]
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:38) ~[bvo.class:?]
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80) ~[bvm.class:?]
	... 6 more
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1.
```

**Comment by Lumieos** [comment]
Solved upon removal of MAGE.

**Comment by copygirl** [comment]
Poked @asiekierka about it.

**Comment by copygirl** [comment]
Well, we removed MAGE from the optional mods a bit ago. I was going to keep this up to see whether the mod will receive an update but I think it's unlikely, so I'm closing this issue.
